"""fix id column

Revision ID: 2914cc35022e
Revises: 78aaee3c7f43
Create Date: 2025-07-02 14:58:50.714266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2914cc35022e'
down_revision: Union[str, Sequence[str], None] = '78aaee3c7f43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use explicit SQL with USING clause
    op.execute("ALTER TABLE products ALTER COLUMN id TYPE INTEGER USING id::integer")
    op.execute("ALTER TABLE products ALTER COLUMN id SET NOT NULL")
    op.execute("ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("ALTER TABLE products ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE products ALTER COLUMN id TYPE VARCHAR USING id::varchar")

    # ### end Alembic commands ###
